name: Build ImGui Menu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Crucial for fetching the ImGui components!

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build Mod Menu
        run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Subway-ImGui-Menu
          path: out/
          
